/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hotel_Alura;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Index j = new Index();
                j.setDefaultCloseOperation(Index.EXIT_ON_CLOSE);
                j.setTitle("Bienvenido");
                j.setLocationRelativeTo(null);
                j.setVisible(true);

                /**
                 *
                 */
                j.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent we) {
                        int result = JOptionPane.showConfirmDialog(j,
                                "¿Desea salir?", "Cerrar ",
                                JOptionPane.YES_NO_OPTION);
                        if (result == JOptionPane.YES_OPTION) {
                            j.setDefaultCloseOperation(j.EXIT_ON_CLOSE);
                        } else if (result == JOptionPane.NO_OPTION) {
                            j.setDefaultCloseOperation(j.DO_NOTHING_ON_CLOSE);
                        }
                    }
                });
                /**
                 *
                 */

            }
        });
    }
}
